# Generated by Django 4.2.3 on 2023-07-25 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='none', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ac87631a-4e34-4f99-9c04-5bc456f12171'), editable=False, primary_key=True, serialize=False),
        ),
    ]
