# Generated by Django 4.2.3 on 2023-07-27 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_image_alter_student_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
